### ISSUE TITLE
Scroll box is nearly visible in scroll bar

### ISSUE THREAD

**Issue by pieterkleine** [seanwcom/Red-Graphite-for-Obsidian#10]
I love this theme, and it has been my default for almost a year now.

If there is one improvement I would suggest, it is to lighten de color of the scroll box in the scroll bar, as it is nearly visible. Especially when dealing with large amounts of files this becomes a nuisance, as I am always searching for where the box is positioned.

Thank you for the awesome theme.

**Comment by seanwcom** [comment]
@pieterkleine - apologies for the lack of updates. Unfortunately I just don't have time to keep up with this as much as I'd like to. I have updated the theme to be compatible with the 1.0 release of obsidian. This is a complete rewrite and because I don't have much time for updates, I've tried to simplify things and have really made this mostly a UI theme rather than adjusting any text.
