### ISSUE TITLE
The Font Sizes Don't Match the Preview

### ISSUE THREAD

**Issue by pope** [seanwcom/Red-Graphite-for-Obsidian#11]
I noticed that the font sizes and anti-aliasing in the editor do not match those in the preview rendering. How would you feel about syncing those up?

This is the custom snippet I use to to sync things. If you are cool with the idea, I can send a PR.

```
/* Otherwise the fonts in preview look a bit chonky on my mac */
div.markdown-preview-view {
  font-variant-ligatures: contextual;
  -webkit-font-smoothing: antialiased;
}

.cm-header, h1, h2, h3, h4, h5, h6 {
  font-weight: 600;
}
.cm-header-1, .markdown-preview-view h1 {
  font-size: 2rem;
  line-height: 3rem;
}
.cm-header-2, .markdown-preview-view h2 {
  font-size: 1.5rem;
}
.cm-header-3, .markdown-preview-view h3 {
  font-size: 1.2rem;
}
.cm-header-4, .markdown-preview-view h4 {
  font-size: 1.125rem;
}
.cm-header-5, .markdown-preview-view h5,
.cm-header-6, .markdown-preview-view h6 {
  font-size: 1rem;
}

/* Setting this here since my selectors above took presidence over the originally declared selector */ 
.cm-formatting-header {
  font-size: 0.6rem;
}
```

For context:

Before:
![Before](https://user-images.githubusercontent.com/2941/117388606-e9c58080-ae9f-11eb-9b3f-8bd1a5ba2af4.png)

After:
![After](https://user-images.githubusercontent.com/2941/117388641-f3e77f00-ae9f-11eb-887e-fb87940a8ae5.png)

**Comment by seanwcom** [comment]
@pope - apologies for the lack of updates. Unfortunately I just don't have time to keep up with this as much as I'd like to. I have updated the theme to be compatible with the 1.0 release of obsidian. This is a complete rewrite and because I don't have much time for updates, I've tried to simplify things and have really made this mostly a UI theme rather than adjusting any text.
