### ISSUE TITLE
Nested tags incorrect highlight

### ISSUE THREAD

**Issue by akhashogji** [seanwcom/Red-Graphite-for-Obsidian#12]
Hi,

While using nested tags, the first part of the tag is not highlighted (line 5). It works for some nested tags, while others, no.
<img width="167" alt="Screen Shot 2021-05-20 at 7 57 38 PM" src="https://user-images.githubusercontent.com/52230109/119019228-a55cd900-b9a5-11eb-97aa-efa7798955c0.png">

**Comment by seanwcom** [comment]
@akhashogji - apologies for the lack of updates. Unfortunately I just don't have time to keep up with this as much as I'd like to. I have updated the theme to be compatible with the 1.0 release of obsidian. This is a complete rewrite and because I don't have much time for updates, I've tried to simplify things and have really made this mostly a UI theme rather than adjusting any text.
