### ISSUE TITLE
Rendered checkbox color

### ISSUE THREAD

**Issue by gallagherman** [seanwcom/Red-Graphite-for-Obsidian#8]
Right now the rendered checkbox color is blue. Any way to change it to the red accent color used everywhere?

**Comment by seanwcom** [comment]
Checkboxes have been a thorn in my side that I've put off for too long. I'll figure something out for sure. :)

**Comment by seanwcom** [comment]
@gallagherman - apologies for the lack of updates. Unfortunately I just don't have time to keep up with this as much as I'd like to. I have updated the theme to be compatible with the 1.0 release of obsidian. This is a complete rewrite and because I don't have much time for updates, I've tried to simplify things and have really made this mostly a UI theme rather than adjusting any text.
